---
title: "Cool Title"
output:
  html_notebook:
    toc: yes
    toc_float: yes
  html_document:
    df_print: paged
    toc: yes
---

Standard libraries
```{r}
rm(list = ls())
options(scipen=999) # scientific notation

library(data.table)
library(ggplot2)
library(caret)
library(plotly)
library(dplyr)
library(DT)
library(pander)
library(plotly)
library(xts)
library(reshape2)
library(arules)

#devtools::install_github("luisalejandrolee/utilucho")
library(utilucho)

#source("scripts/data_cleaning_and_preparation.R")

```

# Import

```{r}
# File names contain the sample size used. Need for the import (must match
# a run of the preparation file to save files with this sample)
sample_size <- 5000
lags <- 2

folder <- "data/staging/"
file_dt <- paste0("master_n", sample_size , "_lags", max(lags), ".csv")
dt <- fread(paste0(folder, file_dt))

```

# Cleaning (again, of course)
```{r}
# choose only some interesting "purchases". Related to the models' target variable
tx <- dt[t_credito_new > 0] # acquired a credit card
#dt[t_credito_loss > 0] # credit card churn



# Replace zeros with NA
tx <- as.data.frame(tx)
tx[tx == 0] <- NA
tx <- as.data.table(tx)


# delete na's (this means losing months of lag with no data. Could be set to zero)
#tx <- na.omit(tx)

# delete columns not needed for market basket
cols_to_del <- c("num_id", "periodo", "t_credito_diff")
tx[, (cols_to_del) := NULL]
# rename (just an index)
setnames(tx, "V1", "id") 

# filter some months?


# All columns as factors, needed to run the apriori algorithm
tx[, (names(tx)) := lapply(.SD, as.factor), .SDcols = names(tx)]


```

# Market basket analysis

```{r}
rules <- apriori(tx, parameter = list(supp = 0.2, conf = 0.85, maxlen = 3),
                 appearance = list(rhs="t_credito_new=1"))
#?apriori
```

```{r}
inspect(rules)
```

```{r}

```














