---
title: "Cool Title"
output:
  html_notebook:
    toc: yes
    toc_float: yes
  html_document:
    df_print: paged
    toc: yes
---

Standard libraries
```{r}
rm(list = ls())
options(scipen=999) # scientific notation

library(data.table)
library(ggplot2)
library(caret)
library(plotly)
library(dplyr)
library(DT)
library(pander)
library(plotly)
library(xts)

#devtools::install_github("luisalejandrolee/utilucho")
library(utilucho)

source("scripts/data_cleaning_and_preparation.R")

```

# Import

```{r}
folder <- "data/raw/"

files <- c("mes_201706", "mes_201707", "mes_201708", "mes_201709", "mes_201710",
           "mes_201711", "mes_201712", "mes_201801", "mes_201802", "mes_201803",
           "mes_201804", "mes_201805", "mes_201806")

all_months <- import_as_list(folder, files)

```

# Clean data (first stage)
```{r}

cols_to_del <- c("TIPO_ID", "tipo_id2", "_NAME_", "CONSTRUCTOR")

# Make ID as character, remove columns, change PERIODO to date format,
# and format column names
clean_dt_in_list(all_months, cols_to_del)

```

# Sample data

I have tried with up to one million clients, and seems to be manageable in memory
```{r}

dts_sampled <- get_samples_dts(all_months, 1000000, frac = FALSE) # sample data
dt <- rbindlist(dts_sampled) # merge all sampled months in a single data.table

# Check how many clients of the original sample remain month after month

#for(i in 1:length(dts_sampled)){
#  print(nrow(dts_sampled[[i]]))
#}
dt
```



# Clean data (second stage)
## Check duplicates
```{r}
# check how many duplicates per month
dup <- dt[, .(num_id, duplicated(num_id)), by = periodo][V2 == TRUE]
dup[, .N, by = periodo]
```
## Remove duplicates
```{r}
# remove duplicate clients in the same month
dup <- dt[, duplicated(num_id), by = periodo] # keeps in V1 if duplicated
dt <- dt[dup$V1 == FALSE] # keep non-duplicated
```


```{r}

```

```{r}

```

```{r}

```

```{r}

```

# Create target variable

```{r}
# make it for tarjeta de credito, but in the function leave it as chosen for any product

```


```{r}
# replace nas with zeros (create function. Also make some functions to give give median, etc)

# check values for each product: max number of products per client
# decide if making an upper bound

# create lag variables for each (create function)
# create adquisition variables: when there's a new product (as a dummy) and when dropping one
# create lags for adquisition variables as well



# Check and analyiza data
## check some stats (create shiny app!.. for time series)
## check correlations
## do a market basket analysis!

# are there products usually bought together?
# does it usually happen that when buying a credit card, another product is always owned?

```


```{r}

# bind data (now that there are less columns)

# particular divisions (chosen by experimenting memory allowance)
#months_2017 <- rbindlist(all_months[1:7])
#months_2018 <- rbindlist(all_months[8:13])


#dt <- rbindlist(list(months_2017, months_2018))
#rm(months_2017, months_2018) # delete old files

#rm(all_months) # delete long list with all months
```























